[project]
name = "data-modeling-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pandas", "seaborn", "matplotlib", "pip", "scikit-learn", "pyqt5"]

